name: Docker Build

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
#      - name: Install Yarn
#        run: npm install -g yarn
      - name: Setup and build
        working-directory: ./newclient
        run: |
          yarn
          yarn build

  build:
    name: Run docker build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Run docker build
        working-directory: ./newclient
        run: docker build --build-arg GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }}
